# Generated by Django 4.2.7 on 2023-11-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equivalences.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecognizedCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "ugd_subject",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "unl_recognized_subject",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equivalences.program",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equivalences.section",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="program",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="equivalences.university",
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "prerequisites",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("weekly_hours", models.IntegerField(blank=True, null=True)),
                ("total_hours", models.IntegerField(blank=True, null=True)),
                ("term", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "teaching_mode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equivalences.section",
                    ),
                ),
            ],
        ),
    ]
