# Generated by Django 4.2.7 on 2023-12-04 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equivalences", "0002_alter_course_section_alter_program_university_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="equivalences.program",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="recognizedcourse",
            name="program",
        ),
        migrations.RemoveField(
            model_name="recognizedcourse",
            name="section",
        ),
        migrations.RemoveField(
            model_name="section",
            name="program",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="RecognizedCourse",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
    ]
