# Generated by Django 4.2.7 on 2023-12-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equivalences", "0005_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equivalence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_course_name", models.CharField(max_length=255)),
                ("destination_course_code", models.CharField(max_length=50)),
                ("destination_course_name", models.CharField(max_length=255)),
                (
                    "destination_university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equivalences_destination",
                        to="equivalences.university",
                    ),
                ),
                (
                    "origin_university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equivalences_origin",
                        to="equivalences.university",
                    ),
                ),
            ],
        ),
    ]
