# Generated by Django 4.2.7 on 2023-12-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equivalences", "0006_equivalence"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
