# Generated by Django 4.2.7 on 2023-12-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("equivalences", "0008_alter_studyplan_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="equivalence",
            name="origin_program",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equivalences_origin_program",
                to="equivalences.program",
            ),
            preserve_default=False,
        ),
    ]
