# Generated by Django 4.2.7 on 2023-12-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "equivalences",
            "0010_rename_destination_course_name_equivalence_destination_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="equivalence",
            name="destination_program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equivalences_destination_program",
                to="equivalences.program",
            ),
        ),
        migrations.AlterField(
            model_name="equivalence",
            name="destination_university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equivalences_destination",
                to="equivalences.university",
            ),
        ),
        migrations.AlterField(
            model_name="equivalence",
            name="origin_university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equivalences_origin",
                to="equivalences.university",
            ),
        ),
    ]
