# Generated by Django 4.2.7 on 2023-12-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equivalences", "0012_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="report",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
